### ISSUE TITLE
Output difference between Python and R

### ISSUE THREAD

**Issue by adityaponnada** [mHealthGroup/MIMSunit#18]
**Describe the bug**
I am running this package inside my python script using rpy2. The output format and the output values seem to differ a lot for the same set of parameters.

Code in R:
`mims_df <- MIMSunit::mims_unit(test_df, dynamic_range = c(-8, 8), epoch = "1 sec")`

Code in Python:
```
with localconverter(ro.default_converter + pandas2ri.converter):
    r_from_pd_df = ro.conversion.py2rpy(raw_data_csv)

# Convert dynamic range into R list
r_g_range = FloatVector(DYNAMIC_RANGE)

mims_df = get_mims(r_from_pd_df, dynamic_range=r_g_range, epoch='1 sec')

with localconverter(ro.default_converter + pandas2ri.converter):
    pd_from_r_df = ro.conversion.rpy2py(mims_df)
```
The date time column has been changed to datetime object before being converted to R data frame within Python. In addition, the accel values are already divided by 9.8 (g) to convert them into gs

**Expected behavior**
The output should be the same as that of the MIMS unit when running in R

**Screenshots**
This is the difference in the output:

R output:-
	
```
HEADER_TIME_STAMP             MIMS_UNIT
1	2020-05-30 23:21:02	-0.01000000
2	2020-05-30 23:21:03	2.79030598
3	2020-05-30 23:21:04	1.21460003
4	2020-05-30 23:21:05	1.64683472
5	2020-05-30 23:21:06	0.99221082
6	2020-05-30 23:21:07	0.37537341
7	2020-05-30 23:21:08	0.63504703
8	2020-05-30 23:21:09	0.18989219
```

This is the output from Python:- 
```
HEADER_TIME_STAMP,MIMS_UNIT
2020-05-30 23:21:02.534000-05:00,-0.01
2020-05-30 23:21:03.004000-05:00,0.2822196508193671
2020-05-30 23:21:04.004000-05:00,0.11480857414889588
2020-05-30 23:21:05.004000-05:00,0.16657279112558554
2020-05-30 23:21:06.004000-05:00,0.09474452994111793
2020-05-30 23:21:07.004000-05:00,0.03585255989478915
2020-05-30 23:21:08.004000-05:00,0.0606708953707094
2020-05-30 23:21:09.004000-05:00,0.018071350713853674
2020-05-30 23:21:10.004000-05:00,0.015923177830656325
2020-05-30 23:21:11.004000-05:00,0.014400738300671727
```

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome

**Comment by qutang** [comment]
You should confirm the input data looks exactly the same. Also, try to take a look at r2py about how it runs R codes in python. Does it compile R code or call R runtime? How is it converting data types? How does it handle package dependencies?

**Comment by adityaponnada** [comment]
input data is the same file. I can verify the conversions

**Comment by qutang** [comment]
Does it support any R packages? There could be many reasons it can go wrong. Data conversion could be the problem, especially the timestamp conversion.

**Comment by adityaponnada** [comment]
I think the mims output is close enough but the timestamp format is messed up. rpy2 is meant to run r package scripts in python. I am trying to check the state intermediate file that is an r dataframe

**Comment by adityaponnada** [comment]
When I print the intermediate R dataframe, it looks correct:

```
R converted data frame
    HEADER_TIME_STAMP X_ACCELATION_METERS_PER_SECOND_SQUARED
0 2020-05-30 23:21:02                            -0.06926224
1 2020-05-30 23:21:02                            -0.07044184
2 2020-05-30 23:21:02                            -0.06886735
3 2020-05-30 23:21:02                            -0.07004592
4 2020-05-30 23:21:02                            -0.06847653
5 2020-05-30 23:21:02                            -0.06965510
  Y_ACCELATION_METERS_PER_SECOND_SQUARED Z_ACCELATION_METERS_PER_SECOND_SQUARED
0                            0.009231633                               1.003650
1                            0.008253061                               1.007806
2                            0.009231633                               1.005117
3                            0.010209184                               1.003650
4                            0.008986735                               1.005117
5                            0.009720408                               1.005850 
```

The timestamps are also correct. But milliseconds part is missing. is that why the timestamp in the mims file looks weird?

**Comment by qutang** [comment]
Yes. That's why the entire values are messed up. milliseconds have to be correct.

**Comment by adityaponnada** [comment]
So far I figured that the actual MIMS value is correct in both python and R. In R I forgot to change it to g which I did in Python.
Also figured that the output data frame in python from the R code is correct:
 ```
   HEADER_TIME_STAMP   MIMS_UNIT
1 2020-05-30 23:21:02 -0.01000000
2 2020-05-30 23:21:03  0.28221965
3 2020-05-30 23:21:04  0.11480857
4 2020-05-30 23:21:05  0.16657279
5 2020-05-30 23:21:06  0.09474453
6 2020-05-30 23:21:07  0.03585256
```

But when converting this to pandas df, it messes up the timestamp

**Comment by qutang** [comment]
Great! Then I'll chose the issue.
