### ISSUE TITLE
Converting MIMSunit to raw data 

### ISSUE THREAD

**Issue by Dkonishi3** [mHealthGroup/MIMSunit#23]
Hello. I have a dataset that contains MIMS data for the x, y, and z axis, but it does not contain the raw data. Is there a way to convert this to raw count data using this library? Thank you.

**Comment by qutang** [comment]
I'm sorry but there is no way to convert MIMSunit back to raw accelerometer data. It is not a reversible algorithm. 

To clarify, the raw count data (I assume you mean Actigraph count) is a different summary measurement based on the raw accelerometer data, which has a different underlying meaning from MIMSunit. And we currently do not have a conversion equation between these two measurements. But feel free to develop your own.
