### ISSUE TITLE
Difference in spline defaults

### ISSUE THREAD

**Issue by muschellij2** [mHealthGroup/MIMSunit#27]
**Describe the bug**
Should the extrapolation method use the same interpolation as if you set `use_extrapolation = FALSE`?

It seems like the default method for interpolation in the extrapolate function to be natural splines:
https://github.com/mHealthGroup/MIMSunit/blob/master/R/extrapolate.R#L101
but the default interpolation is `linear`:
https://github.com/mHealthGroup/MIMSunit/blob/master/R/mims_unit.R#L390

Given that the default is natural splines in the interpolate function:
https://github.com/mHealthGroup/MIMSunit/blob/master/R/interpolate.R#L47
I wasn't sure if this was intended or a bug.  I wanted to see the effect on different splines for interpolation, in conjunction with extrapolation, but I may need to pass in already-interpolated data as a workaround.

**Comment by qutang** [comment]
We don’t use spline interpolation when the flag is false. You may think the spline interpolation is part of the extrapolation algorithm.

However, we still have to resample the signal in a safe way and the safest way (without changing the shape of the signal unexpectedly if there are many maxed out values) is to use linear interpolation, a bandlimited interpolation may also work but still, it may change the shape of the signal with maxed out values.

Qu
