### ISSUE TITLE
Bug in colnames of interpolated data

### ISSUE THREAD

**Issue by muschellij2** [mHealthGroup/MIMSunit#28]
**Describe the bug**
This line would indicate that you'd want the columns to be INTERPOLATED_X/Y/Z, but it doesn't do that: https://github.com/mHealthGroup/MIMSunit/blob/master/R/interpolate.R#L101

It should likely be:
```r
names(results)[2:ncols] = paste("INTERPOLATED", names(results)[2:ncols], sep = "_")
```
But I don't know if that will mess anything up.

**Comment by qutang** [comment]
No, it shouldn't have any impact.
