### ISSUE TITLE
How to define the method in the mims_unit

### ISSUE THREAD

**Issue by zl138453** [mHealthGroup/MIMSunit#30]
Hi,

I have a question, in the function of aggregate_for_mims, you assuming the method="trapz", however, we I ran mims_unit, I have no way to update the method from "trapz" to "sum"

Please let me know how to fix it
Thanks
Lenny

**Comment by qutang** [comment]
Use `custom_mims_unit` where you can customize the algorithm. However, be careful these customized algorithms need to be validated and the manuscript only provides validation for the proposed algorithm.

**Comment by zl138453** [comment]
Thank you very much, I will double check about it
