### ISSUE TITLE
MIMSunit removed from the CRAN due to failing tests

### ISSUE THREAD

**Issue by l-k-** [mHealthGroup/MIMSunit#37]
Hello! I wanted to use MIMSunit for some of my work, but I see that it got removed from CRAN. Do you have plans on making it available on CRAN again? Thank you!

https://cloud.r-project.org/web/packages/MIMSunit/index.html

Package ‘MIMSunit’ was removed from the CRAN repository.
Formerly available versions can be obtained from the archive.
Archived on 2021-10-28 as check problems were not corrected in time.
A summary of the most recent check results can be obtained from the check results archive.
Please use the canonical form https://CRAN.R-project.org/package=MIMSunit to link to this page.

**Comment by qutang** [comment]
Will look into this. For now, please use the github version.

**Comment by qutang** [comment]
This has been resolved. You should be able to download from CRAN.
