### ISSUE TITLE
Release to CRAN

### ISSUE THREAD

**Issue by qutang** [mHealthGroup/MIMSunit#6]

**Comment by qutang** [comment]
Pending now.

https://github.com/mHealthGroup/MIMSunit/commit/b1a92035b4f8fe511e089595126cb32a1b3f0305

**Comment by muschellij2** [comment]
What is the timeline for this do you think?  In order to use some software in our class, we require only CRAN/Bioconductor, so we wanted to check in.

**Comment by qutang** [comment]
It has been several iterations since the last submission. They have a strict policy on the package. However, I would expect it gets passed in two weeks. I'll update the website as soon as it gets passed.

Please subscribe to the issue so that you can be notified in time.

Thank you for your patience.

**Comment by muschellij2** [comment]
Thanks for the response.  I'm subscribed.
